// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hsnndsfpxabvhlarmujg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhzbm5kc2ZweGFidmhsYXJtdWpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3Mjk3ODAsImV4cCI6MjA2NTMwNTc4MH0.pGB3WZX04zHZH3pllOBxAGp54Omfqi17u9y-l4JACz0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);